version: '3'
services:
    se_base:
        build: ./se_base
        image: se_base:latest
        command: ls
    se90:
        build: se90
        depends_on:
            - se_base
        volumes: 
            - ~:/root
        container_name: se90
        # Use "devices" to pass gatekeepers into containers if desired:
        #devices:
        #    - /dev/sdk:/dev/sdk
        #    - /dev/sdl:/dev/sdl
        working_dir: /root
        hostname: dockerized_se90
        stdin_open: true
        tty: true
        command: /bin/bash
        privileged: true
    se84:
        build: ./se84
        depends_on:
            - se_base
        volumes: 
            - ~:/root
        container_name: se84
        # Use "devices" to pass gatekeepers into containers if desired:
        #devices:
        #    - /dev/sdk:/dev/sdk
        #    - /dev/sdl:/dev/sdl
        working_dir: /root
        hostname: dockerized_se84
        stdin_open: true
        tty: true
        command: /bin/bash
        privileged: true
    se83:
        build: ./se83
        depends_on:
            - se_base
        volumes: 
            - ~:/root
        container_name: se83
        # Use "devices" to pass gatekeepers into containers if desired:
        #devices:
        #    - /dev/sdk:/dev/sdk
        #    - /dev/sdl:/dev/sdl
        working_dir: /root
        hostname: dockerized_se83
        stdin_open: true
        tty: true
        command: /bin/bash
        privileged: true
    se82:
        build: ./se82
        depends_on:
            - se_base
        volumes: 
            - ~:/root
        container_name: se82
        # Use "devices" to pass gatekeepers into containers if desired:
        #devices:
        #    - /dev/sdk:/dev/sdk
        #    - /dev/sdl:/dev/sdl
        working_dir: /root
        hostname: dockerized_se82
        stdin_open: true
        tty: true
        command: /bin/bash
        privileged: true
    se81:
        build: ./se81
        depends_on:
            - se_base
        volumes: 
            - ~:/root
        container_name: se81
        # Use "devices" to pass gatekeepers into containers if desired:
        #devices:
        #    - /dev/sdk:/dev/sdk
        #    - /dev/sdl:/dev/sdl
        working_dir: /root
        hostname: dockerized_se81
        stdin_open: true
        tty: true
        command: /bin/bash
        privileged: true
    se76:
        build: ./se76
        depends_on:
            - se_base
        volumes: 
            - ~:/root
        container_name: se76
        # Use "devices" to pass gatekeepers into containers if desired:
        #devices:
        #    - /dev/sdk:/dev/sdk
        #    - /dev/sdl:/dev/sdl
        working_dir: /root
        hostname: dockerized_se76
        stdin_open: true
        tty: true
        command: /bin/bash
        privileged: true
