#!/bin/sh

echo
echo
echo "#############################################"
echo
echo "Dockerized SYMCLI"
echo
echo "- For SYMCLI 7.4, type 'se74'"
echo "- For SYMCLI 7.6, type 'se76'"
echo "- For SYMCLI 8.0, type 'se8'"
echo
echo "The home directory in each SYMCLI container should"
echo "be mapped to your host computer's home directory;"
echo "so all of your files should be visible from $HOME."
echo
echo "Navigate to the directory containing your SYMAPI DB,"
echo "and then set the SYMCLI_DB_FILE environment variable"
echo "to the SYMAPI DB filename."
echo
echo "For example: export SYMCLI_DB_FILE=symapi_db.bin"
echo
echo "Bugs? Contact sean.cummins@emc.com."
echo
echo "#############################################"
echo
echo
